version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4.0
        environment:
          CXX: g++-6
    steps:
      - checkout
      - run:
          name: install
          command: |
            sudo bash -c 'echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" >> /etc/apt/sources.list.d/unstable.list'
            sudo apt-get -y update
            sudo apt-get -y install -t unstable g++-6
            npm install
      - run:
          name: coverage
          command: npm run ci-coverage
